### ISSUE TITLE
[FR] Add hotkey to switch output device?

### ISSUE THREAD

**Issue by Hukuma1** [G-Stas/Volumey#1]
Great app! Not sure if you're taking feature requests, but here is one just in case. ;)

I got headphones and speakers. Would love to bind a hotkey (e.g. `F4`) to switch between the output devices. I was thinking a simple toggle function, but I guess you could also extend it to be to specific devices for a hotkey as well.

<img width="272" alt="win10sound" src="https://user-images.githubusercontent.com/54511555/132997102-e39ac62d-0483-495a-83c8-4a89f7c76003.png">

**Comment by G-Stas** [comment]
Thanks! Yes, I accept feature requests.
Sounds like a nice feature!

**Comment by G-Stas** [comment]
Took me a bit more than expected because I had to change settings page layout, but it's done: 9dd64ef9e7f5ad98cd228cc621bc6dcf814b39ab
Will push the update to Microsoft Store soon!

**Comment by Hukuma1** [comment]
Just tried it! Awesome. Thanks so much.

Is it possible to add a toggle function though? e.g. if you only have two sound devices (headphones, speakers) you could bind one button `F4` to switch between them? So instead of having headphones on `F4` and speakers on `F5`, you can press `F4` to switch between them back and forth? (cycle)

**Comment by G-Stas** [comment]
I don't think there is a place for cycle function, since individual hotkeys is a more powerful tool to do the exact same thing with more flexibility.
Invoking Windows UI isn't possible via third party code. 
But I'll think about adding muting hotkeys & popups for volume changes, etc.
