### ISSUE TITLE
Ability to drag the slider after being clicked not on the handle

### ISSUE THREAD

**Issue by AncuL001** [G-Stas/Volumey#10]
if you click on the slider but not the handle, you can't drag the handle

![](https://i.imgur.com/o3vKOkV.gif)

how it should be:
![](https://i.imgur.com/NblTVmf.gif)

**Comment by AncuL001** [comment]
@G-Stas when are you going to update it on Microsoft Store? since it's a major QOL improvement for me

**Comment by G-Stas** [comment]
> @G-Stas when are you going to update it on Microsoft Store? since it's a major QOL improvement for me

Submitted the update, might take up to several days for Store to process it.
