### ISSUE TITLE
Hover text tray icon

### ISSUE THREAD

**Issue by tippf3hlr** [G-Stas/Volumey#12]
at my machine (win11) the hover text for Volumey is "ToolTip".
Would be nice if it were Volumey or somewhat like the default one {audio device} - {volume}

**Comment by tippf3hlr** [comment]
btw pop up mode is great thanks

**Comment by G-Stas** [comment]
This is a known issue on Windows 11 that I already fixed in e6e033d5f38612b0f4f4d8d527c52b7f50718697 but haven't pushed to the Store yet.

**Comment by tippf3hlr** [comment]
you always fix things before I notice them, how boring
