### ISSUE TITLE
Support for multiple monitors | Remember last opened position

### ISSUE THREAD

**Issue by furyzenblade** [G-Stas/Volumey#22]
The Volumey window only opens on the monitor which is set as the main display. It would be nice to be able to specify on which display the window should appear, or at least remember the last opened position.

![NVIDIA_Share_z0VFVarMro](https://user-images.githubusercontent.com/38463479/159163213-1208546c-f9db-4ae9-90c3-98d30b92f884.gif)

![ApplicationFrameHost_HzuMiGK2Cj](https://user-images.githubusercontent.com/38463479/159162988-a4eba9a3-5ce8-48dd-941c-035182e5551f.png)

**Comment by G-Stas** [comment]
Added remembering last position of the window as an optional feature: 7fa0eae242b3d1f60bceb4c8c2e7ac89f911cbab
