### ISSUE TITLE
Feature Request: Hotkey for "Foreground Application" Volume

### ISSUE THREAD

**Issue by fuba82** [G-Stas/Volumey#26]
hi there,

i use a little tool i've written years ago in Delphi with just the function to Increase/Decrease the Volume of the  
"Currently active Foreground Window" with a Hotkey.

Maybe you can add this to your App because it seems very easy to do as your code already got ALL what is needed :D
Just grab the ProcessID of the Foreground App and then the ProcessName from the ProcessID like this:
```c#
[DllImport("user32.dll", SetLastError = true)]
static extern IntPtr GetForegroundWindow();

[DllImport("user32.dll", SetLastError = true)]
static extern uint GetWindowThreadProcessId(IntPtr hWnd, out uint lpdwProcessId);

IntPtr handle = GetForegroundWindow();

uint processId;
if (GetWindowThreadProcessId(handle, out processId) > 0)
{
    Console.WriteLine(Process.GetProcessById((int)processId).ProcessName);
}
```
i know i can do it myself and pull request then but i think you know your code better then me ;)

greetings!

**Comment by G-Stas** [comment]
Added this feature: 0d1a1059c19d786982e545e11b09b92ccd924351

Didn't test it much, but works fine for me.

**Comment by fuba82** [comment]
thank you very much!
i will test it :)
