### ISSUE TITLE
Non-windows store version?

### ISSUE THREAD

**Issue by gimple** [G-Stas/Volumey#27]
I was wondering, is there a particular reason why the download for this is only available through the windows store?  I am a user and fan of the app, but I am removing all apps from my system that rely upon the windows store -- any chance that we could get a download version that is available outside of that arena?  I'd be happy to provide a mirror for it if necessary.

Thanks.

**Comment by G-Stas** [comment]
No particular reason, actually. I just wanted to host the app somewhere and to make it easy accessible. More to that, Microsoft Store provided OS integration with the app, auto updates and some metrics of the app usage which I've always liked to check.

I'll make a non-store version, which will probably be available from Releases page.

**Comment by G-Stas** [comment]
[Done!](https://github.com/G-Stas/Volumey/releases/tag/1.4.2.0)
I'll make non-store releases from now on. Non-store version can also update itself.
