### ISSUE TITLE
ModernFlyout compatibility

### ISSUE THREAD

**Issue by Artaherzadeh** [G-Stas/Volumey#29]
Hi
After installing this app ModernFlyout got disabled and I had to run it again.
Also if you check the Ink Workspace app, the design and colors are the same as Windows 11 but Volumey is a bit different from Windows 11 app ( the colors, opacity and the opening effect
It's better if they feel like it's part of Windows 11.

**Comment by G-Stas** [comment]
Hello. 
There is no proper way to match Windows 11 style in WPF. You can't make nice and smooth window animations, there is no Acrylic or Mica, so I'm not going to waste my time on mimicking it as Ink Workspace does it.
As for ModernFlyout, I couldn't reproduce it. If you have some more specific instructions to  recreate the problem, please reopen the issue.
