### ISSUE TITLE
Change default device by hotkey - stops working after a while

### ISSUE THREAD

**Issue by 1balint** [G-Stas/Volumey#30]
https://i.imgur.com/HzJc5KJ.jpeg

F3 is for my monitor's speakers. 
When I set it up it works fine, but after a while, it stops working, while F4 still works. 
Then I remove it and it works again. 

Any ideas what I can do so I don't need to search Volumey every time it stops working? 

Thanks! I really enjoy the program for this, it was gamechanger for me until it stopped :(

**Comment by G-Stas** [comment]
Does this happen during the same session when you initially set up hotkeys, or does it happen after several restarts of your computer or the application?

Does the hotkey for speakers keeps being blocked in the OS when it stops working? 
When you register the hotkey for some action it gets blocked for any other operation in the OS, it's very unlikely the hotkey itself stops working after a while but still better to check that.

Another reason for that could be speakers changing its internal ID somehow, despite it should be permanent as I understand that.
Do you interact with speakers somehow, for example disable it in the sound control panel, disconnect or turn off monitor?

**Comment by 1balint** [comment]
HI G-Stas! 

I'll observe it more I think it only does after a restart. As of now, it works after it's in sleep mode. 

`Does the hotkey for speakers keeps being blocked in the OS when it stops working?`
Not sure what that means - it's simply F3 - I'm not aware of anything else using or trying to use it. 

I don't disable that speaker or change settings. 

Thanks, I'll get back to you again when it stops, so I have more info.

**Comment by 1balint** [comment]
So now I had to restart windows and it stopped working. So seems like that's the correlation.

**Comment by cwdsgn** [comment]
1. amazing work.
2. I recently experience a similar issue: My hotkey for output device stopped working and could not reset to the hotkey I had originally used  (Ctrl+Shift+Page UP)

> Does the hotkey for speakers keeps being blocked in the OS when it stops working?
> When you register the hotkey for some action it gets blocked for any other operation in the OS, it's very unlikely the hotkey itself stops working after a while but still better to check that.

^ this may be the case for me - unsure of my specific circumstances - will comment again if I learn more.  ✌️‍

**Comment by G-Stas** [comment]
Finally, I have encountered it. The problem was that the devices just randomly changed their internal unique IDs, which are actually should be "tied to the device installation and only change if the user upgrades the device driver, or if the user uninstalls the device, and installs it again", according to the docs.

I've added searching for registered devices additionally by their names to fix this.
