### ISSUE TITLE
Mute instead of turning the volume down to zero

### ISSUE THREAD

**Issue by Dmitriy-1251** [G-Stas/Volumey#32]
When the volume is reduced to zero, if a different volume has been set for the left and right speakers, the balance is reset to zero on both. 
It is suggested that when moving from 1 to 0, instead of lowering the volume, use the mute parameter, which does not reset the balance

![image](https://user-images.githubusercontent.com/50748183/184613316-d2379615-dee0-4ba1-9bfb-8ca313228865.png)

![image](https://user-images.githubusercontent.com/50748183/184613632-97dbbe64-ac37-4ceb-953a-1bb549ddc467.png)

![image](https://user-images.githubusercontent.com/50748183/184614271-2cce7919-8757-4faf-9610-2c565853b02c.png)

**Comment by G-Stas** [comment]
Added this as an optional feature: 6575197446d9a8bb275377c599579b6b7671a7fa
It can be enabled in the output device hotkeys tab. But it works only for hotkeys volume changes, user will still be able to change volume to 0 explicitly in the mixer view, which will reset the balance.
