### ISSUE TITLE
[Feature Request] Scroll on tray icon to change master volume

### ISSUE THREAD

**Issue by rp1231** [G-Stas/Volumey#35]
It would be a nice feature to be able to change the master volume by scrolling on the tray icon

**Comment by G-Stas** [comment]
I tried to implement this feature before and [wrote about it there](https://github.com/G-Stas/Volumey/issues/3#issuecomment-1016620318). There is a problem with detecting the exact position of the icon, and I'm not sure whether to add this feature or not.
