### ISSUE TITLE
Multiple Monitor Setup not compatible/unsupported

### ISSUE THREAD

**Issue by furyzenblade** [G-Stas/Volumey#38]
commit from: #22

bug comment: https://github.com/G-Stas/Volumey/commit/7fa0eae242b3d1f60bceb4c8c2e7ac89f911cbab#r82285540
> Using "SystemParameters.VirtualScreenHeight" and "SystemParameters.VirtualScreenWidth" will not work when using multiple monitors. As the monitors don't form a simple rectangle.
Screens can have different resolutions and positions.
Same for the "(this.Left + this.Width) > 0" check, it does not consider a multi monitor setup, when moving it "off screen" it might just be on another/second monitor on the left so "this.Left" will be negative and the check will return false, resetting the position even though the window was visible, just on another monitor.

Window position resets when moving the Volumey window to another monitor and then reopening it.
![Recording](https://cdn.discordapp.com/attachments/559140416365133868/1012723733661749319/Recording.gif)

Example case:
![VS](https://cdn.discordapp.com/attachments/559140416365133868/1012723550056108073/VS.png)
![VS_FullScreenshot](https://cdn.discordapp.com/attachments/559140416365133868/1012723550408421407/VS_FullScreenshot.jpg)
![Display_Settings](https://cdn.discordapp.com/attachments/559140416365133868/1012723550702010489/DisplaySettings.png)
(in my particular case I'm using two 2560x1440 monitors but monitor 2 is still the primary monitor, I just moved the taskbar)

**Comment by G-Stas** [comment]
Implemented selector of the screen to use for displaying and removed remembering last window position: a0ec1face9aad27d09d71090ee7539ab3470be88
