### ISSUE TITLE
Many closed applications remained and duplicated in the list

### ISSUE THREAD

**Issue by atooy** [G-Stas/Volumey#39]
Many closed applications show and remain duplicated in the list even after closed.
Such as "audiodg" and "browser".
"browser" is the worst, for duplicating three times.
These applications won't disappear until Volumey is restarted.
![image](https://user-images.githubusercontent.com/13001564/188466378-07c6a927-6854-4c98-8d31-f03ebaf9598e.png)

**Comment by G-Stas** [comment]
What is that browser? Will try to trace the issue by using it.

**Comment by thewan056** [comment]
<img width="288" alt="image" src="https://user-images.githubusercontent.com/24851051/207110267-72390730-91a7-43b3-adb9-c6db3196d268.png">

I am seeing this issue as well. In my case QRSL it is the executable file for the game Tower of Fantasy
https://www.toweroffantasy-global.com/

Would be nice if we can hide entries/apps that we don't really care about, or if its for some reason showing up in volume control but doesn't actually output any sound so there is no reason to be there.

**Comment by PandaSPUR** [comment]
Same issue here with Genshin Impact.
The entries stay in Volumey and eventually causes Volumey to lag horribly or just freeze.

**Comment by G-Stas** [comment]
I guess I fixed this: ef003422735c48e390c9d4d5a07f792dd52de3e8, tested with the QRSL
