### ISSUE TITLE
Screen selector displays the window and OSD on incorrect locations on the external monitor.

### ISSUE THREAD

**Issue by rp1231** [G-Stas/Volumey#41]
If I select the window or OSD to display on the external monitor connected to my laptop,
The volume window just shows up in the upper right corner of my laptop monitor,
And the OSD shows up in very weird locations on the external monitor.

**Comment by G-Stas** [comment]
Was the external monitor connected before the app was started or after that? What are the resolutions of your screens? Does OSD notifications display in weird locations for any type of position and indent, or only for a specific position and indent?

**Comment by G-Stas** [comment]
The resolution detection was working correctly, but there were problems with placing the windows on the right position with scaling enabled, which I think I fixed. 
Also added disabling of the horizontal slider with centered OSD notifications.
