### ISSUE TITLE
The change default devices button doesn't need a dropdown

### ISSUE THREAD

**Issue by rp1231** [G-Stas/Volumey#42]
<img width="300" alt="Screenshot_20221115_083124" src="https://user-images.githubusercontent.com/47380919/201816230-8740aff2-50fb-4dbc-b363-2b0c6f4f1017.png">

It doesn't need to be hidden behind a dropdown menu as it has only one option.
Instead, the icon for the option can be directly used in the place of the gear icon.
And maybe a tooltip can be used for the text?

**Comment by G-Stas** [comment]
Done: 08b54c3229fcce90ff9a243ba0e44da28b70f092
I guess resolves the #19 as well?
