### ISSUE TITLE
Баг или фича

### ISSUE THREAD

**Issue by Griga81745** [G-Stas/Volumey#43]
При нажатии на иконку звука (Скрин ниже)
![изображение](https://user-images.githubusercontent.com/75415245/206942041-38e2bd2e-7de9-4324-9be5-8237aa743df9.png)
Приложение открывается не на основном экране, указанной в виндовс
У меня есть монитор от ноутбука, которым я не пользуюсь, и основной монитор.

**Comment by G-Stas** [comment]
Звучит как баг. Я переписал логику работы с дисплеями в последнем обновлении, обновите и напишите, пожалуйста, по результатам.

**Comment by Griga81745** [comment]
![изображение](https://user-images.githubusercontent.com/75415245/207756106-76edd4d5-c584-4d0c-989e-7736a144c5a7.png)
Всё так же открывается на том экране, и + баг

**Comment by Griga81745** [comment]
Всё так же открывается на том экране, и + баг
![изображение](https://user-images.githubusercontent.com/75415245/207756240-222d6b9a-2829-454f-9459-f745f6152b3e.png)

**Comment by Griga81745** [comment]
> 

Баг случается не всегда
Открыл сейчас и всё оке
Но он всё так же открывается не на том экране

**Comment by Griga81745** [comment]
Всё работает

**Comment by Griga81745** [comment]
Всё работает
