### ISSUE TITLE
Feature Request: Custom Icon for Output Device?

### ISSUE THREAD

**Issue by valsamis-d** [G-Stas/Volumey#44]
Great app! Thanks!

Is there a way to provide a custom icon for the selected output device. For example, use a Jabra icon if a Jabra Speakerphone is the default output device.

Dimitrios

**Comment by thewan056** [comment]
Go to your Control Panel and open Sound. Double click or click the Properties button for the device you wish to change the icon for. Click the Change Icon button. Volumey follows the device icon set here, so changing the icon here changes the icon in Volumey.

**Comment by valsamis-d** [comment]
It worked just fine :) Thank you, @thewan056 !
