### ISSUE TITLE
Icon not showing up for some apps

### ISSUE THREAD

**Issue by hotsno** [G-Stas/Volumey#49]
Minor bug but I'm not getting an icon for some apps (in my fairly limited use, only Genshin Impact). The icon does show up in the volume mixer in Windows 11 settings and in EarTrumpet's mixer.

![image](https://user-images.githubusercontent.com/71658949/223076863-2ee80267-07cc-4ece-ad7d-116b7747e431.png)

**Comment by G-Stas** [comment]
It's the access rights issue when Volumey can't access the .exe file launched with admin rights (Genshin Impact .exe) to parse its icon info. You could launch Volumey with admin rights, so it would have access to other .exe files launched with admin rights. 

Looks like there are some other ways of doing this without requiring admin rights, which I have to research.
