### ISSUE TITLE
"Block registered hotkeys in the OS"

### ISSUE THREAD

**Issue by Cireelim** [G-Stas/Volumey#5]
When the lever is "ON" I can use hotkeys for ex. "PowerToys" in Windows. But when it's "OFF" I can't. And then I can use duplicate hotkeys in Volumey. Is this really how it's supposed to work? For me it feels it should be the other way around. Am I wrong?
And I want to use all hotkeys in Windows And be able to have duplicate hotkeys in Volumey - is that possible?

**Comment by Cireelim** [comment]
The reset of the app data didn't work. It's still "ON" but I can use my other apps hotkeys. This might be fixed in an upcomming update?

**Comment by G-Stas** [comment]
Update is released, I've cut these features for now.
