### ISSUE TITLE
Frequent crashes and/or freezes

### ISSUE THREAD

**Issue by daddy-cool** [G-Stas/Volumey#60]
Hi,

since a few months Volumey randomly will either freeze (tray icon is there but does not react) or silenty crash/quit.
If its frozen I just terminate it in the Task manager, then when started again it will work normally again until such time when it will randomly dissappear.

I think the issue(s) correlate to changing audio devices and/or time running as I never notice it freezing/crashing and just find it either frozen or gone after some time away from the PC.
When adding/removing an audio device I sometimes can get it to freeze.

I believe this issue started happing after some bigger Windows 11 Update in April/May since I never noticed any issues before.
Any way I can provide some logs?

Running Windows 11, Intel i9-12900K with E-Cores disabled, Nvidia RTX 3080Ti.
normally using USB DAC, sometimes using HDMI for audio.
No sleep enabled, system is always awake/responsive

**Comment by daddy-cool** [comment]
After changing a few settings the crashes/freezes seemed to have stopped:

- disabled "pop up mode"
- disabled "always on top"
- disabled "osd notifications" (they work anyway)
- disabled "display on any volume change" (it seems to work anyway)
- disabled "display output device control at the bottom"

I'm not sure which one of these changes actually fixed the issue, I assume its "display output device control at the bottom".

**Comment by REEEV3S** [comment]
Me too, really frustrating to the point of not wanting to touch the program at all.
for me it seems random, i uninstalled microsoft version and then installed through github and it was fine for a week until the issue returned, program just crashes and stops responding and the only way to restart it is to force stop and reopen

windows 10
ryzen 5 5600x
rtx 3060ti
32gb ram

**Comment by daddy-cool** [comment]
I switched over to https://github.com/irzyxa/Volume2/ which offers all I needed from Volumney without crashes
