### ISSUE TITLE
Feature Request: Minimize on system tray at start up

### ISSUE THREAD

**Issue by panoc** [G-Stas/Volumey#61]
is it possible to implement this feature ?

**Comment by rdaraujo** [comment]
I second this :)
I've disabled the stock volume tray icon and now I'm using Volumey on systray as a replacement.
A silent option would be great:
`Volumey.exe --silent`

**Comment by G-Stas** [comment]
The app already has the '-minimized' parameter, which is used when you enable launching at OS startup

**Comment by rdaraujo** [comment]
Thanks true.
Thank you!
